# Generated by Django 4.2.2 on 2023-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_account_remove_listing_band_delete_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
