# Generated by Django 4.2.2 on 2023-06-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_account_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
